### ISSUE TITLE
ESM dynamic require error

### ISSUE THREAD

**Issue by revmischa** [hugomrdias/iso-url#271]
Built my project as ESM with esbuild

Got error:
```
  "errorMessage": "Dynamic require of \"url\" is not supported",
  "trace": [
    "Error: Dynamic require of \"url\" is not supported",
    "    at file:///var/task/index.mjs:1:811",
    "    at null.<anonymous> (/node_modules/iso-url/src/url.js:3:42)",
    "    at file:///var/task/index.mjs:1:891",
    "    at null.<anonymous> (/node_modules/iso-url/index.js:8:5)",
    "    at file:///var/task/index.mjs:1:891",
```

Possible to not do a dynamic `require()`?

**Comment by hugomrdias** [comment]
can you add a code sample please ?

**Comment by revmischa** [comment]
I tried to come up with a quick and easy way to reproduce on the command-line. I got a somewhat different result, I don't know why it's trying to use the browser version on import:

```shell
echo "import 'iso-url'" >> import.js
npx esbuild --format=esm --bundle --target=node14 import.js > import.bundle.js
node import.bundle.js
```

```
/Users/cyber/dev/platform/import.bundle.js:37
    var URL = self.URL;
              ^

ReferenceError: self is not defined
    at node_modules/iso-url/src/url-browser.js (/Users/cyber/dev/platform/import.bundle.js:37:15)
    at __require (/Users/cyber/dev/platform/import.bundle.js:9:50)
    at node_modules/iso-url/index.js (/Users/cyber/dev/platform/import.bundle.js:188:9)
    at __require (/Users/cyber/dev/platform/import.bundle.js:9:50)
    at Object.<anonymous> (/Users/cyber/dev/platform/import.bundle.js:201:30)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
```

I was able to work around the original error with this [EXTREMELY SHADY HACK](https://github.com/evanw/esbuild/pull/2067#issuecomment-1073039746)

**Comment by hugomrdias** [comment]
you need `--platform node` in that cmd

**Comment by hugomrdias** [comment]
as for dynamic requires on a ESM build been this a cjs module thats a pretty nasty combination. you should just avoid it

**Comment by revmischa** [comment]
Ok so if my app is ESM I shouldn't use iso-url?

**Comment by hugomrdias** [comment]
You can just dont do dynamic requires, but to be honest you should not needs this module anymore. Node has proper URL now and legacy parse/format method should really be avoided.
